// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daawhxrxhvdxqhtuvimj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYXdoeHJ4aHZkeHFodHV2aW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODEzNTYsImV4cCI6MjA1Nzg1NzM1Nn0.0neIwFzQuEXjG0jkNdXWoX5PBbU69T9zOLYz68VmmzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);